services:
  # DVWA (PHP/Apache + MariaDB)
  dvwa:
    image: ghcr.io/digininja/dvwa:latest
    pull_policy: always
    environment:
      - DB_SERVER=dvwa-db
    depends_on:
      - dvwa-db
    ports:
      - "4280:80" # http://localhost:4280
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  dvwa-db:
    image: docker.io/library/mariadb:10
    environment:
      - MYSQL_ROOT_PASSWORD=dvwa
      - MYSQL_DATABASE=dvwa
      - MYSQL_USER=dvwa
      - MYSQL_PASSWORD=p@ssw0rd
    volumes:
      - dvwa_data:/var/lib/mysql
    restart: unless-stopped

  # OWASP Benchmark (Java/Tomcat via Maven Cargo, in-memory)
  owasp-benchmark:
    build:
      context: ./owasp-benchmark
    ports:
      - "8443:8443" # https://localhost:8443/benchmark/
    environment:
      - MAVEN_OPTS=-Xms512m -Xmx2g
    restart: unless-stopped
    healthcheck:
      # Self-signed cert, so use -k
      test: ["CMD", "sh", "-lc", "curl -k -fsS https://localhost:8443/benchmark/ >/dev/null"]
      interval: 30s
      timeout: 20s
      retries: 10
      start_period: 120s

volumes:
  dvwa_data:
    driver: local

